import { StyleSheet, Platform } from 'react-native';
import { colors } from '../../../theme/colors';
import { typography } from '../../../theme/typography';
import { spacing } from '../../../theme/spacing';
import { radii } from '../../../theme/radii';
import { shadows } from '../../../theme/shadows';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: 0,
    backgroundColor: colors.bgPrimary,
    ...Platform.select({
      web: {
        flex: 0,
        minHeight: '100%',
      },
      default: null,
    }),
  },
  flex: {
    flex: 1,
    minHeight: 0,
    ...Platform.select({
      web: {
        flex: 0,
        minHeight: '100%',
      },
      default: null,
    }),
  },
  scroll: {
    flex: 1,
    minHeight: 0,
  },
  content: {
    flexGrow: 1,
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    paddingHorizontal: spacing[6],
    paddingTop: spacing[12],
    paddingBottom: spacing[12],
  },
  webContent: {
    flexGrow: 0,
    minHeight: '100%',
  },
  hero: {
    marginBottom: spacing[6],
  },
  heroHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing[4],
  },
  heroLeft: {
    flex: 1,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: colors.brandPrimary,
    borderRadius: radii.full,
    backgroundColor: colors.brandSubtle,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    marginBottom: spacing[3],
  },
  heroBadgeText: {
    color: colors.brandText,
    fontSize: 12,
    fontWeight: '900',
  },
  title: {
    color: colors.white,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    ...typography.body,
    color: colors.textTertiary,
    lineHeight: 22,
    marginTop: spacing[2],
    maxWidth: 520,
    fontWeight: '600',
  },
  newProductButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.xl,
    backgroundColor: colors.brandPrimary,
    paddingHorizontal: spacing[5],
  },
  newProductButtonText: {
    color: colors.white,
    ...typography.body,
    fontWeight: '900',
  },
  errorPanel: {
    borderWidth: 1,
    borderColor: colors.error,
    borderRadius: radii.xl + 2,
    backgroundColor: colors.errorSubtle,
    padding: spacing[3] + 2,
    marginBottom: spacing[3] + 2,
  },
  errorTitle: {
    ...typography.bodySm,
    color: colors.errorText,
    fontWeight: '900',
  },
  errorText: {
    ...typography.bodySm,
    color: colors.errorText,
    lineHeight: 19,
    marginTop: spacing[1],
    fontWeight: '700',
  },
  listSection: {
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii['2xl'],
    backgroundColor: colors.bgSurface,
    padding: spacing[6],
    ...shadows.sm,
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[3],
    marginBottom: spacing[5],
  },
  eyebrow: {
    ...typography.overline,
    color: colors.brandText,
    fontWeight: '900',
  },
  sectionTitle: {
    ...typography.h2,
    color: colors.textPrimary,
    fontWeight: '900',
    marginTop: spacing[1],
  },
  refreshButton: {
    minHeight: 40,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.brandPrimary,
    borderRadius: radii.xl,
    paddingHorizontal: spacing[3],
  },
  refreshButtonText: {
    color: colors.brandText,
    fontSize: 12,
    fontWeight: '900',
  },
  bulkActions: {
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii['2xl'],
    backgroundColor: colors.bgSurface,
    marginBottom: spacing[5],
    zIndex: 10,
  },
  selectionText: {
    flex: 1,
    minWidth: 0,
    ...typography.bodySm,
    color: colors.textSecondary,
    lineHeight: 18,
    fontWeight: '800',
  },
  generateAdButton: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.xl,
    paddingHorizontal: spacing[4],
  },
  generateAdButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '900',
  },
  emptyText: {
    ...typography.bodySm,
    color: colors.textTertiary,
    fontWeight: '700',
    paddingVertical: spacing[4],
  },
  productList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[4],
    width: '100%',
    zIndex: 1,
  },
  productCard: {
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.xl + 2,
    backgroundColor: colors.bgSurfaceHover,
    paddingHorizontal: spacing[4],
    paddingTop: spacing[4],
    paddingBottom: spacing[6],
    gap: spacing[4],
    flexGrow: 0,
    flexShrink: 0,
    ...Platform.select({
      web: {
        transitionProperty: 'all',
        transitionDuration: '200ms',
        cursor: 'pointer',
      },
      default: null,
    }),
  },
  productCardHover: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.bgSurfaceActive,
    transform: [{ translateY: -3 }],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  productCardPressed: {
    transform: [{ scale: 0.99 }],
  },
  productCardSelected: {
    borderColor: colors.brandPrimary,
    backgroundColor: colors.brandSubtle,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  avatarBox: {
    width: 56,
    height: 56,
    borderRadius: radii.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  avatarGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEmoji: {
    fontSize: 24,
  },
  checkbox: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radii.lg,
    backgroundColor: colors.bgInput,
  },
  checkboxSelected: {
    borderColor: colors.brandText,
    backgroundColor: colors.brandPrimary,
  },
  checkboxText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: '900',
  },
  checkboxDisabled: {
    borderColor: colors.borderDefault,
    backgroundColor: colors.borderDefault,
    opacity: 0.5,
  },
  productInfo: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  productName: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
    color: colors.textPrimary,
  },
  platformAndPrice: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[2],
  },
  productPrice: {
    fontSize: 16,
    color: colors.white,
    fontWeight: '900',
  },
  platformBadge: {
    paddingHorizontal: spacing[2.5],
    paddingVertical: 3,
    borderRadius: radii.full,
    borderWidth: 1,
  },
  platformBadgeText: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  badgeMeli: {
    backgroundColor: 'rgba(254, 240, 138, 0.1)',
    borderColor: 'rgba(254, 240, 138, 0.3)',
  },
  badgeTextMeli: {
    color: '#FFE600',
  },
  badgeShopee: {
    backgroundColor: 'rgba(255, 87, 34, 0.1)',
    borderColor: 'rgba(255, 87, 34, 0.3)',
  },
  badgeTextShopee: {
    color: '#FF5722',
  },
  badgeAmazon: {
    backgroundColor: 'rgba(255, 153, 0, 0.1)',
    borderColor: 'rgba(255, 153, 0, 0.3)',
  },
  badgeTextAmazon: {
    color: '#FF9900',
  },
  badgeOther: {
    backgroundColor: 'rgba(148, 163, 184, 0.1)',
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  badgeTextOther: {
    color: '#94A3B8',
  },
  featurePills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[1],
  },
  featurePill: {
    paddingHorizontal: spacing[2],
    paddingVertical: 2,
    borderRadius: radii.md,
    backgroundColor: colors.bgInput,
  },
  featurePillText: {
    fontSize: 10,
    color: colors.textTertiary,
    fontWeight: '700',
    maxWidth: 90,
  },
  cardActions: {
    flexDirection: 'row',
    gap: spacing[2],
    marginTop: 'auto',
  },
  detailsButton: {
    minHeight: 36,
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    backgroundColor: colors.brandSubtle,
    borderWidth: 1,
    borderColor: colors.brandPrimary,
  },
  detailsButtonText: {
    fontSize: 12,
    color: colors.brandText,
    fontWeight: '900',
  },
  actionButton: {
    minHeight: 36,
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    backgroundColor: colors.bgInput,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  actionButtonText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '900',
  },
  deleteButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    backgroundColor: colors.errorSubtle,
  },
  deleteButtonText: {
    fontSize: 12,
    color: colors.errorText,
    fontWeight: '900',
  },
  fab: {
    position: 'absolute',
    bottom: spacing[6],
    right: spacing[6],
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.brandPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    zIndex: 99,
  },
  fabText: {
    color: colors.white,
    fontSize: 28,
    fontWeight: '600',
    lineHeight: 28,
    textAlign: 'center',
  },
  fabPressed: {
    transform: [{ scale: 0.95 }],
    opacity: 0.9,
  },
  drawerBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.bgOverlay,
    zIndex: 999,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  backdropClickArea: {
    flex: 1,
  },
  drawerContainer: {
    width: 480,
    backgroundColor: colors.bgSurface,
    borderLeftWidth: 1,
    borderLeftColor: colors.borderDefault,
    height: '100%',
    padding: spacing[6],
    shadowColor: '#000',
    shadowOffset: { width: -4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: colors.borderDefault,
    marginBottom: spacing[4],
  },
  drawerTitle: {
    ...typography.h2,
    color: colors.white,
    fontWeight: '900',
  },
  closeDrawerButton: {
    width: 32,
    height: 32,
    borderRadius: radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgInput,
  },
  closeDrawerText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  drawerScroll: {
    flex: 1,
  },
  bottomSheetBackdrop: {
    flex: 1,
    backgroundColor: colors.bgOverlay,
    justifyContent: 'flex-end',
  },
  bottomSheetContent: {
    backgroundColor: colors.bgSurface,
    borderTopLeftRadius: radii['2xl'],
    borderTopRightRadius: radii['2xl'],
    padding: spacing[6],
    maxHeight: '90%',
  },
  bottomSheetDragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.borderStrong,
    alignSelf: 'center',
    marginBottom: spacing[4],
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: colors.borderDefault,
    marginBottom: spacing[4],
  },
  bottomSheetTitle: {
    ...typography.h2,
    color: colors.white,
    fontWeight: '900',
  },
  bottomSheetScroll: {
    maxHeight: 600,
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[2] + 2,
    marginTop: spacing[6],
  },
  pageButton: {
    minHeight: 42,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radii.xl,
    paddingHorizontal: spacing[3],
  },
  pageButtonText: {
    ...typography.bodySm,
    color: colors.textSecondary,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.35,
  },
  pageLabel: {
    ...typography.bodySm,
    color: colors.textTertiary,
    fontWeight: '800',
  },
  pressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.9,
  },
  modalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgOverlay,
    padding: spacing[5],
    zIndex: 1000,
  },
  modalContent: {
    width: '100%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: colors.error,
    borderRadius: radii['2xl'],
    backgroundColor: colors.errorSubtle,
    padding: spacing[4] + 2,
    gap: spacing[3],
  },
  modalTitle: {
    ...typography.h3,
    color: colors.errorText,
    fontWeight: '900',
  },
  modalText: {
    ...typography.body,
    color: colors.errorText,
    lineHeight: 20,
    fontWeight: '700',
  },
  modalButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.xl,
    backgroundColor: colors.error,
    paddingHorizontal: spacing[3] + 2,
  },
  modalButtonText: {
    ...typography.bodySm,
    color: colors.white,
    fontWeight: '900',
  },
  generatedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    width: '100%',
  },
  detailsModalContent: {
    width: '100%',
    maxWidth: 520,
    height: 500,
    maxHeight: '80%',
    borderColor: colors.borderDefault,
    backgroundColor: colors.bgSurface,
    padding: spacing[5],
  },
  detailsModalHeader: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderDefault,
    paddingBottom: spacing[3],
    marginBottom: spacing[3],
  },
  detailsModalTitle: {
    ...typography.h3,
    color: colors.textPrimary,
    fontWeight: '900',
    flex: 1,
  },
  detailsModalScroll: {
    flex: 1,
    width: '100%',
  },
  detailsModalScrollContent: {
    gap: spacing[4],
    paddingBottom: spacing[2],
  },
  detailsModalDivider: {
    height: 1,
    backgroundColor: colors.borderDefault,
    marginVertical: spacing[2],
  },
  detailsModalFieldRow: {
    flexDirection: 'row',
    gap: spacing[4],
  },
  detailsModalHalfField: {
    flex: 1,
    gap: spacing[1],
  },
  detailsCloseButton: {
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.xl,
    backgroundColor: colors.brandPrimary,
    paddingHorizontal: spacing[4],
    marginTop: spacing[2],
  },
  detailsCloseButtonText: {
    ...typography.body,
    color: colors.white,
    fontWeight: '700',
  },
  generatedDetails: {
    borderWidth: 1,
    borderColor: colors.brandActive,
    borderRadius: radii['2xl'],
    backgroundColor: colors.brandSubtle,
    padding: spacing[4],
    gap: spacing[3],
  },
  generatedHeading: {
    ...typography.bodySm,
    color: colors.brandText,
    fontWeight: '900',
  },
  generatedBadge: {
    overflow: 'hidden',
    borderRadius: radii.lg,
    backgroundColor: colors.brandHover,
    color: colors.white,
    fontSize: 10,
    fontWeight: '900',
    paddingHorizontal: spacing[1.5],
    paddingVertical: spacing[0.5],
  },
  generatedField: {
    gap: spacing[1.5],
    backgroundColor: colors.bgInput,
    padding: spacing[3],
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  generatedFieldHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[1],
  },
  copyButton: {
    paddingVertical: 4,
    paddingHorizontal: spacing[2],
    borderRadius: radii.md,
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  copyButtonText: {
    fontSize: 11,
    color: colors.brandText,
    fontWeight: '800',
  },
  generatedLabel: {
    ...typography.overline,
    color: colors.brandText,
    fontWeight: '900',
  },
  generatedValue: {
    ...typography.bodySm,
    color: colors.textPrimary,
    lineHeight: 19,
    fontWeight: '700',
  },
  generatedChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[1],
  },
  generatedChip: {
    borderWidth: 1,
    borderColor: colors.brandHover,
    borderRadius: radii.full,
    backgroundColor: colors.brandSubtle,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
  },
  generatedChipText: {
    ...typography.overline,
    color: colors.brandText,
    fontWeight: '800',
  },
  generatedDate: {
    ...typography.overline,
    color: colors.textTertiary,
    fontWeight: '700',
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgInput,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.xl,
    paddingHorizontal: spacing[3],
    minHeight: 40,
    ...Platform.select({
      web: {
        transitionProperty: 'all',
        transitionDuration: '200ms',
        cursor: 'pointer',
      },
      default: null,
    }),
  },
  searchContainerFocused: {
    borderColor: colors.brandPrimary,
    backgroundColor: colors.bgInputFocus,
  },
  searchIcon: {
    marginRight: spacing[2],
    fontSize: 14,
  },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    paddingVertical: 0,
  },
  actionButtonContainer: {
    gap: 4,
  },
  generateAdButtonActive: {
    backgroundColor: colors.brandPrimary,
  },
  generateAdButtonDisabled: {
    backgroundColor: colors.bgSurfaceActive,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    opacity: 0.6,
  },
  generateAdButtonHover: {
    backgroundColor: colors.brandHover,
  },
  disabledLabel: {
    fontSize: 10,
    color: colors.textTertiary,
    fontWeight: '600',
    marginTop: 2,
  },
  activeSelectionLabel: {
    fontSize: 10,
    color: colors.brandText,
    fontWeight: '800',
    marginTop: 2,
  },
  detailsButtonHover: {
    backgroundColor: colors.brandHover,
  },
  actionButtonHover: {
    backgroundColor: colors.bgSurfaceActive,
    borderColor: colors.borderStrong,
  },
  deleteButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
    ...Platform.select({
      web: {
        transitionProperty: 'all',
        transitionDuration: '200ms',
        cursor: 'pointer',
      },
      default: null,
    }),
  },
  deleteButtonHover: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  deleteButtonText: {
    fontSize: 14,
    color: colors.textTertiary,
  },
  metricsContainer: {
    marginBottom: spacing[6],
    width: '100%',
  },
  metricCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.xl,
    backgroundColor: colors.bgSurface,
    padding: spacing[4],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  metricCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[2],
  },
  metricLabel: {
    ...typography.overline,
    color: colors.textTertiary,
    fontWeight: '800',
  },
  metricIcon: {
    fontSize: 16,
  },
  metricValue: {
    fontSize: 28,
    fontWeight: '900',
    color: colors.textPrimary,
  },
  searchAndFiltersRow: {
    width: '100%',
  },
  filterDropdownsContainer: {
    flexGrow: 0,
    flexShrink: 0,
  },
  bulkActionsRow: {
    width: '100%',
  },
  filterSelectContainer: {
    position: 'relative',
  },
  filterSelectArrow: {
    color: colors.textTertiary,
    fontSize: 10,
    position: 'absolute',
    right: 12,
    top: 15,
    pointerEvents: 'none',
  },
  filterSelectWrapper: {
    position: 'relative',
    zIndex: 20,
    minWidth: 140,
  },
  filterSelectTrigger: {
    height: 40,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    backgroundColor: colors.bgInput,
    paddingHorizontal: spacing[3],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterSelectTriggerText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  filterSelectArrowMobile: {
    color: colors.textTertiary,
    fontSize: 10,
  },
  filterSelectOptionsList: {
    position: 'absolute',
    top: 44,
    left: 0,
    right: 0,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radii.lg,
    backgroundColor: colors.bgSurface,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 99,
  },
  filterSelectOption: {
    paddingVertical: spacing[2.5],
    paddingHorizontal: spacing[3],
    backgroundColor: colors.bgSurface,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderDefault,
  },
  filterSelectOptionSelected: {
    backgroundColor: colors.brandSubtle,
  },
  filterSelectOptionText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  filterSelectOptionTextSelected: {
    color: colors.brandText,
    fontWeight: '800',
  },
  paginationCountText: {
    ...typography.bodySm,
    color: colors.textTertiary,
    fontWeight: '700',
  },
  pageSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1.5],
  },
  pageArrowButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.bgInput,
  },
  pageArrowButtonHover: {
    backgroundColor: colors.bgSurfaceActive,
    borderColor: colors.brandPrimary,
  },
  pageArrowButtonText: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
  },
  pageNumberButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.bgInput,
  },
  pageNumberButtonHover: {
    backgroundColor: colors.bgSurfaceActive,
    borderColor: colors.brandPrimary,
  },
  pageNumberButtonActive: {
    backgroundColor: colors.brandPrimary,
    borderColor: colors.brandPrimary,
  },
  pageNumberButtonText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  pageNumberButtonTextActive: {
    color: colors.white,
    fontWeight: '900',
  },
  userSessionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.xl,
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    marginBottom: spacing[6],
  },
  userWelcomeText: {
    ...typography.bodySm,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  userEmailText: {
    color: colors.brandText,
    fontWeight: '800',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1.5],
    paddingVertical: spacing[1.5],
    paddingHorizontal: spacing[3.5],
    borderRadius: radii.lg,
    backgroundColor: colors.errorSubtle,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  logoutButtonText: {
    ...typography.caption,
    color: colors.errorText,
    fontWeight: '900',
  },
});
