import React, { useState, useRef } from 'react';
import {
  View, Text, TextInput, TouchableOpacity,
  StyleSheet, ActivityIndicator, Alert, KeyboardAvoidingView,
  Platform, StatusBar, useWindowDimensions, Pressable
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { useNavigation } from '@react-navigation/native';
import { StackNavigationProp } from '@react-navigation/stack';
import { useForm, Controller } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useAuth } from '../contexts/AuthContext';
import { RootStackParamList } from '../../../../navigation/AppNavigator';
import { useGoogleAuth } from '../hooks/useGoogleAuth';
import { colors } from '../../../../theme/colors';
import { AIButton } from '../../../../components/DesignSystem';
import { styles } from './LoginScreen.styles';

const schema = z.object({
  email: z.string().email('E-mail inválido').min(1, 'E-mail obrigatório'),
  password: z.string().min(6, 'Mínimo 6 caracteres'),
});

type FormData = z.infer<typeof schema>;
type Nav = StackNavigationProp<RootStackParamList, 'Login'>;

export default function LoginScreen() {
  const { login, loginWithGoogle } = useAuth();
  const navigation = useNavigation<Nav>();
  const [loading, setLoading] = useState(false);
  const [googleLoading, setGoogleLoading] = useState(false);
  const passwordInputRef = useRef<TextInput>(null);

  // Focus and Hover States
  const [emailFocused, setEmailFocused] = useState(false);
  const [passwordFocused, setPasswordFocused] = useState(false);

  const { control, handleSubmit, formState: { errors } } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: { email: '', password: '' },
  });

  const { request, promptAsync } = useGoogleAuth(async (token) => {
    try {
      console.log('[Google Auth] Token generated by Google:', token);
      setGoogleLoading(true);
      await loginWithGoogle(token);
      console.log('[Google Auth] Login successful!');
    } catch (e: any) {
      console.error('[Google Auth] loginWithGoogle error details:', e?.response?.data || e);
      Alert.alert('Erro', e?.response?.data?.message ?? 'Falha ao entrar com Google');
    } finally {
      setGoogleLoading(false);
    }
  });

  const onSubmit = async (data: FormData) => {
    try {
      setLoading(true);
      await login(data);
    } catch (e: any) {
      Alert.alert('Erro', e?.response?.data?.message ?? 'Falha ao entrar');
    } finally {
      setLoading(false);
    }
  };

  const { width } = useWindowDimensions();
  const isDesktop = Platform.OS === 'web' && width >= 768;

  const renderForm = (isMobile: boolean) => (
    <View style={[styles.card, !isMobile && styles.desktopCard]}>
      <Text style={styles.cardTitle}>Entrar</Text>

      <Controller
        control={control}
        name="email"
        render={({ field: { onChange, value } }) => (
          <View style={styles.inputGroup}>
            <Text style={styles.label}>E-mail</Text>
            <View style={[
              styles.inputWrapper,
              emailFocused && styles.inputWrapperFocused,
              errors.email && styles.inputWrapperError
            ]}>
              <Text style={styles.inputFieldIcon}>📧</Text>
              <TextInput
                style={styles.textInputStyle}
                placeholder="seu@email.com"
                placeholderTextColor={colors.textTertiary}
                keyboardType="email-address"
                autoCapitalize="none"
                value={value}
                onChangeText={onChange}
                returnKeyType="next"
                onFocus={() => setEmailFocused(true)}
                onBlur={() => setEmailFocused(false)}
                onSubmitEditing={() => passwordInputRef.current?.focus()}
                blurOnSubmit={false}
              />
            </View>
            {errors.email && <Text style={styles.error}>{errors.email.message}</Text>}
          </View>
        )}
      />

      <Controller
        control={control}
        name="password"
        render={({ field: { onChange, value } }) => (
          <View style={styles.inputGroup}>
            <Text style={styles.label}>Senha</Text>
            <View style={[
              styles.inputWrapper,
              passwordFocused && styles.inputWrapperFocused,
              errors.password && styles.inputWrapperError
            ]}>
              <Text style={styles.inputFieldIcon}>🔒</Text>
              <TextInput
                ref={passwordInputRef}
                style={styles.textInputStyle}
                placeholder="••••••••"
                placeholderTextColor={colors.textTertiary}
                secureTextEntry
                value={value}
                onChangeText={onChange}
                returnKeyType="done"
                onFocus={() => setPasswordFocused(true)}
                onBlur={() => setPasswordFocused(false)}
                onSubmitEditing={handleSubmit(onSubmit)}
              />
            </View>
            {errors.password && <Text style={styles.error}>{errors.password.message}</Text>}
          </View>
        )}
      />

      <AIButton
        title={loading ? 'Entrando...' : 'Entrar'}
        onPress={handleSubmit(onSubmit)}
        disabled={loading}
        loading={loading}
        fullWidth
        style={styles.submitButton}
      />

      <View style={styles.dividerContainer}>
        <View style={styles.dividerLine} />
        <Text style={styles.dividerText}>ou</Text>
        <View style={styles.dividerLine} />
      </View>

      <Pressable
        onPress={() => promptAsync()}
        disabled={!request || googleLoading}
        style={({ pressed, hovered }) => [
          styles.googleButton,
          pressed && styles.pressed,
          hovered && styles.googleButtonHover
        ]}
      >
        <View style={styles.googleButtonInner}>
          {googleLoading ? (
            <ActivityIndicator color={colors.white} />
          ) : (
            <>
              <Text style={styles.googleIcon}>G</Text>
              <Text style={styles.googleButtonText}>Entrar com Google</Text>
            </>
          )}
        </View>
      </Pressable>

      <TouchableOpacity onPress={() => navigation.navigate('Register')} style={styles.link}>
        <Text style={styles.linkText}>Não tem conta? <Text style={styles.linkBold}>Cadastre-se</Text></Text>
      </TouchableOpacity>
    </View>
  );

  return (
    <View style={styles.mainContainer}>
      <StatusBar barStyle="light-content" />
      {isDesktop ? (
        <View style={styles.webContainer}>
          <LinearGradient colors={['#0B1120', '#111827', '#0F172A']} style={styles.visualPane}>
            {/* Ambient Background Glows */}
            <View style={styles.glowOverlay1} />
            <View style={styles.glowOverlay2} />

            <View style={styles.visualContent}>
              <View style={styles.logoRow}>
                <LinearGradient
                  colors={['#3B82F6', '#8B5CF6']}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 1 }}
                  style={styles.logoBadge}
                >
                  <Text style={styles.logoBadgeText}>✨</Text>
                </LinearGradient>
                <Text style={styles.visualTitle}>SellerAI</Text>
              </View>
              
              <Text style={styles.visualSubtitle}>
                Crie anúncios otimizados por IA e aumente suas vendas nos marketplaces.
              </Text>

              {/* Benefits Checklist */}
              <View style={styles.benefitsList}>
                <View style={styles.benefitItem}>
                  <Text style={styles.checkIcon}>✓</Text>
                  <Text style={styles.benefitText}>Gere títulos otimizados</Text>
                </View>
                <View style={styles.benefitItem}>
                  <Text style={styles.checkIcon}>✓</Text>
                  <Text style={styles.benefitText}>Crie descrições persuasivas</Text>
                </View>
                <View style={styles.benefitItem}>
                  <Text style={styles.checkIcon}>✓</Text>
                  <Text style={styles.benefitText}>Publique mais rápido</Text>
                </View>
                <View style={styles.benefitItem}>
                  <Text style={styles.checkIcon}>✓</Text>
                  <Text style={styles.benefitText}>Venda mais no Mercado Livre e Shopee</Text>
                </View>
              </View>
            </View>
          </LinearGradient>
          
          <View style={styles.formPane}>
            <KeyboardAvoidingView behavior="padding" style={styles.formContainer}>
              {renderForm(false)}
            </KeyboardAvoidingView>
          </View>
        </View>
      ) : (
        <LinearGradient colors={['#0B1120', '#111827']} style={styles.mobileContainer}>
          <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.inner}>
            <View style={styles.header}>
              <LinearGradient
                colors={['#3B82F6', '#8B5CF6']}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
                style={styles.badge}
              >
                <Text style={styles.badgeText}>✨</Text>
              </LinearGradient>
              <Text style={styles.title}>SellerAI</Text>
              <Text style={styles.subtitle}>IA para vender mais no{'\n'}Mercado Livre e Shopee.</Text>
            </View>

            {renderForm(true)}
          </KeyboardAvoidingView>
        </LinearGradient>
      )}
    </View>
  );
}


